### ISSUE TITLE
Convert ZJS temp and lux raw values

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#138]
The raw values reported by the REST API server are 11 bit and need to be converted to Celsius/Fahrenheit and Lux. 

For temperature the formula to convert the value can be found here:
http://wiki.seeed.cc/Grove-Temperature_Sensor_V1.2/

Here is an example for the light sensor.
http://wiki.seeedstudio.com/wiki/Grove_-_Light_Sensor_v1.2

**Comment by ttzeng** [comment]
@uhofemei IMHO, OCF has defined data models for [temperature](http://oneiota.org/revisions/1809) and [illuminance ](http://oneiota.org/revisions/1811) resources, I believe we should follow the spec instead of having OCF clients convert the data into specific formats, otherwise we will break existing servers such as the Node [temperature](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/js-servers/temperature.js),  [illuminance](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/js-servers/ambient_light.js), and the native [temperature](https://github.com/01org/SmartHome-Demo/blob/master/sensors/ocf_multi_sensors/x86/src/main.c#L76-L126) servers. If you are referring the [multi-server](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js) in the Zephyr.js repository, it registers resources of type `core.light` and `core.temp`, they might be displayed in the custom resource cards.

**Comment by ichbinblau** [comment]
Hi, @uhofemei @ttzeng . I am a bit confused. Are the resource type `oic.r.sensor.illuminance`  and `oic.r.temperature` ? Are they the same temperature/illunimance server as the original ones? If not, Tonny is right, It may break the existing servers. Or are we going to integrate a new resource type with some customized data formatting?  If you want the new temperature and illuminance sensor data looks the same as the original ones in the temperature and illuminance widgets, would you plz provide me with the new resource type? I will make it a known type and make the formatting.
