### ISSUE TITLE
Cloud portal runs very slowly when no internet connection is available

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#143]
We set-up the IoT to Cloud Smart Home demo without an internet connection and in order to still be able to show the Cloud Portal and analytics, we had a local machine running the `smarthome2loud/smarthome-cloud` docker container. We observed however that it was very slow (to the point of being unusable). We tried different host machine (including a very powerful one equipped with core i7, 32GB of RAM and 350GB of SSD) but to no avail. The problem simply disappeared as soon as we had a live internet connection.

@ichbinblau , could you take a look?

**Comment by ichbinblau** [comment]
Hi, @gvancuts. As the Cloud portal uses Google Material design lite (eg. styles, fonts, javascripts), moments.js(for time zone computing), echarts (for drawing the charts),  the portal downloads these resources before completely loading page (You may want to check the code [here](https://github.com/01org/SmartHome-Demo/blob/master/smarthome-web-portal/templates/home_base.html#L32)). 

Due to the open source code scan, these resources are not supposed to be part of our code.  The portal references these resources hosted by google and cloudflare rather than a local hosting for the time being.  Therefore, the internet access is required, otherwise, the resources and scripts cannot be used to render the complete page. 

If we are going to use the portal in a offline mode, the alternative is to download and host all of them by web server locally in the container.  What do you think?

**Comment by uhofemei** [comment]
To me that means we need to connect the offline gateway to the Internet at least once before we take it to an event so that the cashed content is in sync with upstream.

**Comment by gvancuts** [comment]
Thanks @ichbinblau for the explanation. I did not realise that this is why a connection was needed. It does not sound very straightforward to get rid of that limitation so I'm enclined to just leave things as is and make sure everyone is aware that a network connection is *required* (and not simply optional). In many ways, one would think that a cloud portal always has an internet connection anyway so this is really just only affecting us when setting up demos at specific events and that means we need to make sure we do ask for a wired connection every time.

@uhofemei , I'm not sure this alone would be sufficient. The kit I used this week was connected to the internet last week when you tested it, yet it was not functional.

**Comment by ichbinblau** [comment]
Cos there is an expiration time ( normally one day or more)  for caches, the duration varies depending on different response servers (google and cloudflare).  Per my test today, most resources could be cached by browser and reloaded from local disk except for today's weather, weather forecast for power prediction and google maps which requires Internet access.

**Comment by gvancuts** [comment]
I don't think using caching content would be a reliable options for demos at events. We should make sure that an internet connection (wired) is requested for all demonstrations.
