### ISSUE TITLE
Not possible to log in to the user portal using different credentials from different tabs

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#154]
It is not possible to have multiple tabs opened under different users (different credentials) for the User Portal. I have only tested this on Google Chrome Version 59.0.3071.86 (Official Build) (64-bit) so far.

**Comment by ichbinblau** [comment]
Hi， @gvancuts . It is an expected behavior.  When user signs in, web server creates a session keeping user info for the user and sends back a session id to the client as cookie saved in browser (as you can see below). In that case, server can identify the user for the later requests by the session id. Any further access (open a new tab) to the same domain or url such as \<portal-ip\>:3000 in the browser will lead to the same session id.   It explains why different tabs use the same credential. 
![image](https://user-images.githubusercontent.com/8187638/26959829-f8a18654-4d04-11e7-9be1-ccecbff66383.png)
It is a common practice for many websites. If you firstly sign out Stackoverflow, open a second tab and login again.  Refresh the first tab, the first tab will login the site with the credential saved in the browser cookie. 

In order to have multiple users login, you can open browser in incognito mode or use another browser like FF, Edge. 
<img width="171" alt="untitled" src="https://user-images.githubusercontent.com/8187638/26959943-02477b40-4d06-11e7-8d33-719fc73e1359.png">

**Comment by gvancuts** [comment]
Thanks for the explanation @ichbinblau. Is there an easy way each tab (i.e. new sign-in) could create a new session associated with a different cookie?

**Comment by ichbinblau** [comment]
I will do some study on it. I think it is possible if I can rewrite each request url to random domain.  In that case, the each tab has its own session id.

**Comment by mjkadera** [comment]
Could we just open a new incognito browser or is this option not as elegant as what you are looking for?

**Comment by gvancuts** [comment]
We could and that's good enough for me. I was mostly interested in case there was an easy way to change this. I wouldn't do it if it means too much investigation and a fairly big code change.

**Comment by gvancuts** [comment]
Let's keep this as is for now, closing this issue.
